using System.CodeDom;
using Assets.Scripts.Core.Services;
using MessagePack;

[Union(0, typeof(SpawnData))]
[Union(1, typeof(MovementInputData))]
[Union(2, typeof(InventoryData))]
[Union(3, typeof(AbilityData))]
[Union(4, typeof(IdData))]
[Union(5, typeof(NameData))]
[Union(6, typeof(DescriptionData))]
[Union(7, typeof(StatsData))]
[Union(8, typeof(HealthData))]
[Union(9, typeof(WeaponData))]
[Union(10, typeof(SelectData))]
[Union(11, typeof(CurrencyData))]
[Union(12, typeof(ConnectionData))]
[Union(13, typeof(HeatSourceData))]
[Union(14, typeof(HeatReceiverData))]
[Union(15, typeof(HeatCountData))]
[Union(16, typeof(KeyData))]
[Union(17,typeof(RangeData))]
[Union(18, typeof(GuidData))]
[Union(19, typeof(ActorData))]
[Union(20, typeof(OwnerData))]
[Union(21,typeof(SpawnableData))]
[Union(22, typeof(DriverData))]
[Union(23, typeof(ResourceData))]
[Union(24, typeof(NextAllocatedIdData))]
[Union(25,typeof(RocketData))]
[Union(26,typeof(DestroyData))]
[Union(27, typeof(MaxHeatData))]
[Union(28,typeof(DamageData))]
[Union(29,typeof(VelocityData))]
[Union(30,typeof(DeathData))]
[Union(31,typeof(ProfileData))]
[Union(32,typeof(CurrentDriverData))]
[Union(33,typeof(ShootData))]
[Union(34,typeof(CurrentHeatData))]
[Union(35,typeof(CurrentTargetData))]
[Union(36, typeof(PointsData))]
[Union(37,typeof(KilledByData))]
[Union(38,typeof(AuthorData))]
[Union(39,typeof(KillsData))]
[Union(40,typeof(PositionData))]
[Union(41,typeof(SpawnTimeData))]
[Union(42,typeof(CollectTimeData))]
[Union(43,typeof(ActiveTimeData))]
[Union(44,typeof(DamageMultiplierData))]
[Union(45,typeof(IgnoreSelfHeatData))]
[Union(46,typeof(IgnoreOtherHeatData))]
[Union(47,typeof(RicochetData))]
[Union(48,typeof(RicoShieldData))]
[Union(49,typeof(RouletteData))]
[Union(50,typeof(RocketAutoAimData))]
[Union(51,typeof(NeoData))]
[Union(52,typeof(AttachmentData))]
[Union(53,typeof(ViewMonoData))]
[Union(54,typeof(PhotonViewData))]
[Union(55,typeof(RestrictionData))]
public interface IEntityData { }